name: app_geolocation
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.1 <4.0.0"

dependencies:
  bloc: ^8.1.3
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  geolocator: ^11.0.0
  get_it: ^7.6.7
  google_maps_flutter: ^2.6.0
  permission_handler: ^11.3.0
  rxdart: ^0.27.7

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/images/
  uses-material-design: true
